wrap = "keep" # options: {"keep", "no", INTEGER}
number = true # options: {false, true}
end_of_line = "lf" # options: {"lf", "crlf", "keep"}
validate = true # options: {false, true}
extensions = [ # options: a list of enabled extensions (default: all installed are enabled)
    "gfm",
    "toc",
]

# Python 3.13+ only:
exclude = [] # options: a list of file path pattern strings
